app/src/Entity/Chat.php
<?php

namespace App\Entity;

use App\Repository\ChatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DateTimeImmutable;

#[ORM\HasLifecycleCallbacks] 
#[ORM\Entity(repositoryClass: ChatRepository::class)]
class Chat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'chats')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'chat', orphanRemoval: true)]
    private Collection $messages;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setChat($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getChat() === $this) {
                $message->setChat(null);
            }
        }

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->created_at = new DateTimeImmutable();
        // Optional: also set updated_at at the same time
        $this->setUpdatedAtValue();
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updated_at = new DateTimeImmutable();
    }
}

app/src/Form/ChatType.php
<?php

namespace App\Form;

use App\Entity\Chat;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('owner', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
                'label' => 'Владелец'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chat::class,
        ]);
    }
}

app/src/Controller/ChatController.php
<?php

namespace App\Controller;

use App\Entity\Chat;
use App\Entity\Message;
use App\Form\ChatType;
use App\Form\MessageType;
use App\Repository\ChatRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/chat')]
final class ChatController extends AbstractController
{
    #[Route(name: 'app_chat_index', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function index(ChatRepository $chatRepository): Response
    {
        $user = $this->getUser();

        if (in_array('ROLE_SUPPORT', $user->getRoles())) {
            $chats = $chatRepository->findAll();
        } else {
            $chats = $chatRepository->findBy(['owner' => $user]);
        }

        return $this->render('chat/index.html.twig', [
            'chats' => $chats,
        ]);
    }

    #[Route('/new', name: 'app_chat_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $chat = new Chat();
        $user = $this->getUser();

        $chat->setOwner($user);
        $entityManager->persist($chat);
        $entityManager->flush();

        return $this->redirectToRoute('app_chat_show', ['id' => $chat->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_chat_show', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function show(Request $request, Chat $chat): Response
    {
        $message = new Message();
        $messages = $chat->getMessages()->toArray();

        $form = $this->createForm(MessageType::class, $message, [
            'action' => $this->generateUrl('app_message_new', [
                'chatId' => $chat->getId()
            ])
        ]);

        return $this->render('chat/show.html.twig', [
            'chat' => $chat,
            'messages' => $messages,
            'form' => $form
        ]);
    }

    #[Route('/{id}/edit', name: 'app_chat_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function edit(Request $request, Chat $chat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChatType::class, $chat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_chat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chat/edit.html.twig', [
            'chat' => $chat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chat_delete', methods: ['POST'])]
    #[IsGranted('ROLE_USER')]
    public function delete(Request $request, Chat $chat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $chat->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($chat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_chat_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/chat/_delete_form.html.twig
<form method="post" action="{{ path('app_chat_delete', {'id': chat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chat.id) }}">
    <button class="btn btn-danger">Удалить</button>
</form>

app/templates/chat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mb-3">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

app/templates/chat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Изменить чат{% endblock %}

{% block body %}
    <h1>Изменить чат</h1>

    {{ include('chat/_form.html.twig', {'button_label': 'Изменить'}) }}

    <a href="{{ path('app_chat_index') }}" class="btn btn-primary d-inline-block mb-3">Вернуться к списку</a>

    {{ include('chat/_delete_form.html.twig') }}
{% endblock %}

app/templates/chat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Главная страница чатов{% endblock %}

{% block body %}
    <h1>Главная страница чатов</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Владелец</th>
                <th>Дата создания</th>
                <th>Дата изменения</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
        {% for chat in chats %}
            <tr>
                <td>{{ chat.id }}</td>
                <td>{{ chat.owner.id }}</td>
                <td>{{ chat.createdAt ? chat.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ chat.updatedAt ? chat.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_chat_show', {'id': chat.id}) }}" class="btn btn-secondary">Просмотреть</a>
                    <a href="{{ path('app_chat_edit', {'id': chat.id}) }}" class="btn btn-warning">Изменить</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_chat_new') }}" class="btn btn-success">Создать новый чат</a>
{% endblock %}

app/templates/chat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Чат{% endblock %}

{% block body %}
<h1>Чат</h1>

<div class="card mb-5" style="height: 400px; overflow-y: scroll;">
    <div class="card-body">
        {% for message in messages %}
        <div class="d-flex justify-content-start mb-3">
            <div class="bg-light p-3 rounded" style="max-width: 75%;">
                <div class="mb-1">{{ message.content }}</div>
                <div class="d-flex justify-content-end align-items-center">
                    <div class="text-muted small" title="123">
                        {{ message.createdAt|date('H:i') }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- <div class="d-flex justify-content-start mb-3">
            <div class="bg-light p-3 rounded">
                Привет! Как дела?
            </div>
        </div>
        <div class="d-flex justify-content-end mb-3">
            <div class="bg-primary text-white p-3 rounded">
                Всё отлично, работаю над проектом.
            </div>
        </div> -->
    </div>
</div>


{{ include('message/_form.html.twig') }}

<!-- <div class="input-group mt-3">
    <input type="text" class="form-control" placeholder="Введите сообщение...">
    <button class="btn btn-primary">Отправить</button>
</div> -->

<div class="d-inline-flex flex-column mb-3 row-gap-2">
    <a href="{{ path('app_chat_index') }}" class="btn btn-primary">Вернуться к списку</a>

    <a href="{{ path('app_chat_edit', {'id': chat.id}) }}" class="btn btn-warning">Изменить</a>
</div>


{{ include('chat/_delete_form.html.twig') }}
{% endblock %}